version: 2.1
jobs:
  build:
    working_directory: ~/viewing_party
    docker:
      - image: circleci/ruby:2.4.1
        environment:
          PGHOST: localhost
          PGUSER: viewing_party
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: viewing_party
          POSTGRES_DB: viewing_party_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      #install bundler
      - run: gem install bundler 2.1.4
      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the environment
      - run: cp .sample.env .env

      # Setup the database
      - run: bundle exec rake db:setup

      # Run the tests
      - run: bundle exec rspec